# ===============================================================
# Imeoic - OI Contest
# Author: Imeoic Development Team
# See: https://github.com/imeoic/imeoic/#readme
# ===============================================================


# ---------------------------------------------------------------
# Compatibility Information
# ---------------------------------------------------------------

version: 0.0.1    # Imeoic version number


# ---------------------------------------------------------------
# Contest Information
# ---------------------------------------------------------------

# Contest Basic Information
# Subtitle and Author are optional.
title: NCOI Round 114514
author: NCOI Team
language: zh-CN

# Languages & Compile Information
languages:
  C++: -O2 -std=c++14

# Notes
# Custom notes below the problem information table.
notes:
  - 文件名（程序名和输入输出文件名）必须使用英文小写。
  - C/C++ 中函数 main() 的返回值类型必须是 int，程序正常结束时的返回值必须是 0。
  - 提交的程序代码文件的放置位置请参考各省的具体要求。
  - 因违反以上三点而出现的错误或问题，申述时一律不予受理。
  - 若无特殊说明，结果的比较方式为全文比较（过滤行末空格及文末回车）。
  - 程序可使用的栈空间内存限制与题目的内存限制一致。
  - 全国统一评测时采用的机器配置为：12th Gen Intel(R) Core(TM) i7-12700 2.10 GHz，内存 16GB。上述时限以此配置为准。
  - 只提供 Linux 格式附加样例文件。
  - 评测在当前最新公布的 NOI Linux 下进行，各语言的编译器版本以此为准。
  #- 题目非常简单，请喧哗的同学不要大声 AK。

# Days & Problems Information
days:
  day1:
    title: Day 1
    author:
    time_st: 1926-08-17 08:30
    time_fn: 1926-08-17 13:30
    problems:
      - A
    #  - B
    #  - C
    notes:
  #day2:
  #  title: Day 2
  #  author:
  #  time_st: 1926-08-18 08:30
  #  time_fn: 1926-08-18 13:30
  #  problems:
  #    - E
  #    - F
  #    - G
  #  notes:
