# ===============================================================
# Noci - Problem
# Author: Noci Development Team
# See: https://github.com/Sukwants/Noci/#readme
# ===============================================================


# ---------------------------------------------------------------
# Statement Information
# ---------------------------------------------------------------

# Basic Information
title: 题目
file: problem
author:                   # (optional)
#language: zh-CN

# Statement Particular
type: traditional
#type: interactive
#type: communication
#type: submitting
type_notice: false        # Notice the problem type in front of the problem description.
file_io: true             # Notice the IO methods in the front if the IO format.


# ---------------------------------------------------------------
# Judgement Information
# ---------------------------------------------------------------

# Judgement Settings
time_limit: 1000          # (unit: ms)
memory_limit: 512         # (unit: MB)
tests:
  quantity: 3
  scores:                 # (optional)
    #- 33
    #- 33
    #- 34
subtasks:                 # (optional)
    #- tests: 1
    #  score: 40
    #- tests: 2
    #  score: 60

# Samples Settings
samples:
  quantity: 3
  displayed:
    - 1
